import type { SettingDef } from '../types'
import { FONT_OPTIONS } from '../../utils/fonts'

export const scheme: SettingDef[] = [
  /* ── Bubble ────────────────────────────────────────────── */
  {
    key: 'chat-msg-bg',
    section: 'Bubble',
    type: 'color',
    label: 'Background',
    default: '#1a1a1a',
  },
  {
    key: 'chat-msg-color',
    section: 'Bubble',
    type: 'color',
    label: 'Text Color',
    default: '#e5e2e1',
  },
  {
    key: 'chat-scrollbar-thumb',
    section: 'Bubble',
    type: 'color',
    label: 'Border Color',
    default: '#888888',
  },
  {
    key: 'chat-border-width',
    section: 'Bubble',
    type: 'range',
    label: 'Border Width',
    min: 0,
    max: 10,
    default: 2,
    unit: 'px',
  },
  {
    key: 'chat-border-radius',
    section: 'Bubble',
    type: 'range',
    label: 'Corner Radius',
    min: 0,
    max: 30,
    default: 12,
    unit: 'px',
  },
  {
    key: 'chat-msg-padding',
    section: 'Bubble',
    type: 'range',
    label: 'Padding',
    min: 4,
    max: 30,
    default: 8,
    unit: 'px',
  },
  {
    key: 'chat-tail-offset',
    section: 'Bubble',
    type: 'range',
    label: 'Tail Offset',
    min: -20,
    max: 10,
    default: -8,
    unit: 'px',
  },
  {
    key: 'chat-avatar-vertical-offset',
    section: 'Bubble',
    type: 'range',
    label: 'Avatar Vertical Offset',
    min: -20,
    max: 20,
    default: 0,
    unit: 'px',
  },
  {
    key: 'chat-max-width',
    section: 'Bubble',
    type: 'range',
    label: 'Max Width',
    min: 200,
    max: 800,
    default: 400,
    unit: 'px',
  },

  /* ── Username ──────────────────────────────────────────── */
  {
    key: 'chat-username-color',
    section: 'Username',
    type: 'color',
    label: 'Username Color',
    default: '#d6baff',
  },
  {
    key: 'chat-username-font-size',
    section: 'Username',
    type: 'range',
    label: 'Size',
    min: 10,
    max: 40,
    default: 13,
    unit: 'px',
  },
  {
    key: 'chat-username-font-weight',
    section: 'Username',
    type: 'toggle',
    label: 'Bold',
    default: true,
  },

  /* ── Message ──────────────────────────────────────────── */
  {
    key: 'chat-message-font-size',
    section: 'Message',
    type: 'range',
    label: 'Content Font Size',
    min: 10,
    max: 48,
    default: 14,
    unit: 'px',
  },

  /* ── Avatar ────────────────────────────────────────────── */
  {
    key: 'chat-avatar-width',
    section: 'Avatar',
    type: 'range',
    label: 'Size',
    min: 16,
    max: 80,
    default: 24,
    unit: 'px',
  },
  {
    key: 'chat-avatar-margin-top',
    section: 'Avatar',
    type: 'range',
    label: 'Vertical Offset',
    min: 0,
    max: 60,
    default: 0,
    unit: 'px',
  },

  /* ── Common ────────────────────────────────────────────── */
  {
    key: 'chat-container-opacity',
    section: 'Common',
    type: 'range',
    label: 'Container Opacity',
    min: 0,
    max: 100,
    default: 100,
    unit: '%',
  },
  {
    key: 'chat-message-opacity',
    section: 'Common',
    type: 'range',
    label: 'Message Opacity',
    min: 0,
    max: 100,
    default: 100,
    unit: '%',
  },
  {
    key: 'chat-message-spacing',
    section: 'Common',
    type: 'select',
    label: 'Message Spacing',
    default: 'normal',
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'normal', label: 'Normal' },
      { value: 'comfortable', label: 'Comfortable' },
    ],
  },
  {
    key: 'chat-animation-speed',
    section: 'Common',
    type: 'select',
    label: 'Animation Speed',
    default: 'normal',
    options: [
      { value: 'none', label: 'None' },
      { value: 'slow', label: 'Slow' },
      { value: 'normal', label: 'Normal' },
    ],
  },
  {
    key: 'chat-username-animation',
    section: 'Animation',
    type: 'select',
    label: 'Username Entrance',
    default: 'slide',
    options: [
      { value: 'slide', label: 'Slide Left' },
      { value: 'wiggle', label: 'Wiggle' },
      { value: 'pop', label: 'Pop' },
      { value: 'fade', label: 'Fade' },
    ],
  },
  {
    key: 'chat-message-animation',
    section: 'Animation',
    type: 'select',
    label: 'Message Entrance',
    default: 'slide',
    options: [
      { value: 'slide', label: 'Slide Left' },
      { value: 'bounce', label: 'Bounce' },
      { value: 'pop', label: 'Pop' },
      { value: 'fade', label: 'Fade' },
    ],
  },
  {
    key: 'chat-margin-left',
    section: 'Common',
    type: 'range',
    label: 'Screen Margin Left',
    min: 0,
    max: 100,
    default: 0,
    unit: 'px',
  },
  {
    key: 'chat-font-family',
    section: 'Common',
    type: 'select',
    label: 'Font Family',
    default: 'inherit',
    options: [
      { value: 'inherit', label: 'Default' },
      ...FONT_OPTIONS.map((f) => ({ value: f.value, label: f.label })),
    ],
  },

  /* ── YouTube ──────────────────────────────────────────── */
  {
    key: 'hide-youtube-generic',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Generic Messages',
    default: false,
  },
  {
    key: 'hide-youtube-header',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Chat Header',
    default: false,
  },
  {
    key: 'hide-youtube-footer',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Chat Footer',
    default: false,
  },

  /* ── OBS ───────────────────────────────────────────────── */
  {
    key: 'chroma-key',
    section: 'OBS',
    type: 'toggle',
    label: 'Chroma Key Ready',
    default: false,
  },

  /* ── Visibility ────────────────────────────────────────── */
  {
    key: 'show-avatars',
    section: 'Visibility',
    type: 'toggle',
    label: 'Show Avatars',
    default: true,
  },

  /* ── Role Colors ───────────────────────────────────────── */
  {
    key: 'chat-owner-bg',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Bubble Background',
    default: '#2d1b00',
  },
  {
    key: 'chat-owner-text',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Text',
    default: '#ffb347',
  },
  {
    key: 'chat-owner-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Username',
    default: '#ffb347',
  },

  {
    key: 'chat-mod-bg',
    section: 'Role Colors',
    type: 'color',
    label: 'Mod Bubble Background',
    default: '#001a2d',
  },
  {
    key: 'chat-mod-text',
    section: 'Role Colors',
    type: 'color',
    label: 'Mod Text',
    default: '#47b5ff',
  },
  {
    key: 'chat-mod-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Mod Username',
    default: '#47b5ff',
  },

  {
    key: 'chat-member-bg',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Bubble Background',
    default: '#1a2d00',
  },
  {
    key: 'chat-member-text',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Text',
    default: '#8bcc47',
  },
  {
    key: 'chat-member-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Username',
    default: '#ce93d8',
  },
]
