/**
 * CSS Export utility for OBS Browser Source.
 *
 * Generates a downloadable `.css` file with:
 * - OBS setup instructions in a comment header
 * - The generated chat CSS
 * - CSS variables for easy customization
 */

/* ─── OBS Instructions Header ───────────────────────────────────── */

function generateOBSHeader(options: { themeName?: string; videoId?: string }): string {
  const date = new Date().toISOString().split('T')[0]
  const theme = options.themeName || 'youtube-chat-custom'
  const videoUrl = options.videoId
    ? `https://www.youtube.com/live_chat?v=${options.videoId}`
    : 'https://www.youtube.com/live_chat?v=YOUR_VIDEO_ID'

  return [
    '/* ===================================================================',
    '   YouTube Live Chat — Custom Theme',
    '   Generated by Livicat',
    `   Date: ${date}`,
    `   Theme: ${theme}`,
    '   ====================================================================',
    '',
    '   📋 OBS Browser Source Setup:',
    '   1. Add a Browser Source to your scene',
    `  2. Set URL to: ${videoUrl}`,
    '  3. Set Width/Height (e.g. 400 × 600)',
    '  4. Check "Refresh browser when scene becomes active"',
    '  5. Paste ALL of the CSS below into the "Custom CSS" field',
    '  6. (Optional) Disable audio under "Control audio via OBS"',
    '',
    '   💡 Tips:',
    '   - CSS variables use the --chat-* prefix for easy identification',
    '   - Adjust colors by changing the variable values in :root',
    '   - All rules use !important to override YouTube defaults',
    '   - Edit this file in any text editor and re-paste into OBS',
    '   =================================================================== */',
    '',
  ].join('\n')
}

/* ─── Main Export Generator ─────────────────────────────────────── */

/**
 * Generate a complete OBS-ready CSS file content.
 *
 * @param css - The generated chat CSS string (from settingsToCSS)
 * @param options - Optional metadata for the header
 * @returns Complete CSS file content with OBS instructions
 */
export function generateOBSCSS(
  css: string,
  options: { themeName?: string; videoId?: string } = {}
): string {
  const header = generateOBSHeader(options)
  const body = css || '/* No custom styles applied */'
  return header + body + '\n'
}

/* ─── Browser Download ──────────────────────────────────────────── */

/**
 * Download a CSS string as a `.css` file in the browser.
 *
 * Uses the standard Blob + object URL + anchor.click() pattern.
 * Cleans up the object URL after 1 second.
 */
export function downloadCSSFile(
  cssContent: string,
  filename: string = 'youtube-chat-custom'
): void {
  const safeName = filename
    .replace(/[^a-zA-Z0-9_-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
  const fullFilename = safeName ? `${safeName}.css` : 'youtube-chat-custom.css'

  const blob = new Blob([cssContent], { type: 'text/css;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fullFilename
  anchor.rel = 'noopener'
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)

  // Revoke the object URL after the download has started
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
