/**
 * CSS Export utility for OBS Browser Source.
 *
 * Generates a downloadable `.css` file with:
 * - OBS setup instructions in a comment header
 * - The generated chat CSS
 * - CSS variables for easy customization
 *
 * In Tauri: uses native save dialog + file system write
 * In browser: falls back to Blob download
 */

import { trackEventAsync } from './analytics'
import { save } from '@tauri-apps/plugin-dialog'
import { writeTextFile } from '@tauri-apps/plugin-fs'
import { isTauri } from '@tauri-apps/api/core'

/* ─── OBS Instructions Header ───────────────────────────────────── */

function generateOBSHeader(options: { themeName?: string; videoId?: string }): string {
  const date = new Date().toISOString().split('T')[0]
  const theme = options.themeName || 'youtube-chat-custom'
  const videoUrl = options.videoId
    ? `https://www.youtube.com/live_chat?v=${options.videoId}`
    : 'https://www.youtube.com/live_chat?v=YOUR_VIDEO_ID'

  return [
    '/* ===================================================================',
    '   YouTube Live Chat — Custom Theme',
    '   Generated by Livicat',
    `   Date: ${date}`,
    `   Theme: ${theme}`,
    '   ====================================================================',
    '',
    '   📋 OBS Browser Source Setup:',
    '   1. Add a Browser Source to your scene',
    `  2. Set URL to: ${videoUrl}`,
    '  3. Set Width/Height (e.g. 400 × 600)',
    '  4. Check "Refresh browser when scene becomes active"',
    '  5. Paste ALL of the CSS below into the "Custom CSS" field',
    '  6. (Optional) Disable audio under "Control audio via OBS"',
    '',
    '   💡 Tips:',
    '   - CSS variables use the --chat-* prefix for easy identification',
    '   - Adjust colors by changing the variable values in :root',
    '   - All rules use !important to override YouTube defaults',
    '   - Edit this file in any text editor and re-paste into OBS',
    '   =================================================================== */',
    '',
  ].join('\n')
}

/* ─── Main Export Generator ─────────────────────────────────────── */

/**
 * Generate a complete OBS-ready CSS file content.
 *
 * @param css - The generated chat CSS string (from settingsToCSS)
 * @param options - Optional metadata for the header
 * @returns Complete CSS file content with OBS instructions
 */
export function generateOBSCSS(
  css: string,
  options: { themeName?: string; videoId?: string } = {}
): string {
  const header = generateOBSHeader(options)
  const body = css || '/* No custom styles applied */'
  return header + body + '\n'
}

/* ─── Tauri / Browser Download ──────────────────────────────────── */

/**
 * Helper to safe-name a filename for export.
 */
function safeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
}

/**
 * Download a CSS string as a `.css` file.
 *
 * In Tauri: opens a native save dialog and writes the file via the filesystem plugin.
 * In browser: falls back to Blob + anchor.click().
 */
export async function downloadCSSFile(
  cssContent: string,
  filename: string = 'youtube-chat-custom'
): Promise<void> {
  const fullFilename = `${safeFilename(filename) || 'youtube-chat-custom'}.css`

  try {
    if (isTauri()) {
      // Tauri: native save dialog + file system write
      const savePath = await save({
        defaultPath: fullFilename,
        filters: [{ name: 'CSS Files', extensions: ['css'] }],
      })

      if (!savePath) {
        console.log('[CSS Export] User cancelled save dialog')
        return
      }

      await writeTextFile(savePath, cssContent)
      console.log('[CSS Export] Saved to:', savePath)
    } else {
      // Browser: Blob download fallback
      const blob = new Blob([cssContent], { type: 'text/css;charset=utf-8' })
      const url = URL.createObjectURL(blob)

      const anchor = document.createElement('a')
      anchor.href = url
      anchor.download = fullFilename
      anchor.rel = 'noopener'
      document.body.appendChild(anchor)
      anchor.click()
      document.body.removeChild(anchor)

      setTimeout(() => URL.revokeObjectURL(url), 1000)
      console.log('[CSS Export] Downloaded in browser:', fullFilename)
    }
  } catch (error) {
    console.error('[CSS Export] Failed:', error)
    // Fallback: try browser download as last resort
    try {
      const blob = new Blob([cssContent], { type: 'text/css;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const anchor = document.createElement('a')
      anchor.href = url
      anchor.download = fullFilename
      anchor.rel = 'noopener'
      document.body.appendChild(anchor)
      anchor.click()
      document.body.removeChild(anchor)
      setTimeout(() => URL.revokeObjectURL(url), 1000)
    } catch (fallbackError) {
      console.error('[CSS Export] Fallback also failed:', fallbackError)
    }
  }

  // Track analytics event
  trackEventAsync('css_exported', {
    format: 'css',
    method: 'download',
    had_customizations: cssContent.length > 0,
  })
}
