import type { SettingDef } from '../types'

/**
 * Neon Sticker (Ink Sticker) — theme-specific settings only.
 *
 * Settings shared across all themes live in `src/theme/core.ts`.
 * `coreCssVarMap` maps each core key → this theme's CSS variable name
 * so buildCSSVariables emits the correct `--var-name`.
 */
export const coreCssVarMap: Record<string, string> = {
  bg: 'messageBg',
  'text-color': 'messageColor',
  'username-color': 'usernameColor',
  'container-opacity': 'containerOpacity',
  'message-opacity': 'messageOpacity',
  'message-spacing': 'chat-message-spacing',
  'animation-speed': 'animationSpeed',
  'username-bold': 'chat-username-font-weight',
  'owner-bg': 'ownerBg',
  'owner-text': 'ownerText',
  'mod-bg': 'modBg',
  'mod-text': 'modText',
  'member-bg': 'memberBg',
  'member-text': 'memberText',
  'superchat-bg': 'superchatBg',
  'superchat-text': 'superchatText',
  'membership-bg': 'membershipBg',
  'membership-text': 'membershipText',
}

export const scheme: SettingDef[] = [
  /* ── Typography ─────────────────────────────────────────── */
  {
    key: 'usernameFontSize',
    section: 'Typography',
    type: 'range',
    label: 'Name Size',
    min: 10,
    max: 40,
    default: 14,
    unit: 'px',
  },
  {
    key: 'messageFontSize',
    section: 'Typography',
    type: 'range',
    label: 'Content Font Size',
    min: 10,
    max: 48,
    default: 14,
    unit: 'px',
  },
  {
    key: 'avatarSize',
    section: 'Typography',
    type: 'range',
    label: 'Avatar Size',
    min: 16,
    max: 80,
    default: 28,
    unit: 'px',
  },
  {
    key: 'chat-avatar-vertical-offset',
    section: 'Typography',
    type: 'range',
    label: 'Avatar Vertical Offset',
    min: -20,
    max: 60,
    default: 0,
    unit: 'px',
  },

  /* ── Effects ────────────────────────────────────────────── */
  {
    key: 'skewAngle',
    section: 'Effects',
    type: 'range',
    label: 'Skew Angle',
    min: -45,
    max: 45,
    default: 0,
    step: 1,
    unit: 'deg',
  },
  {
    key: 'shadowOffset',
    section: 'Effects',
    type: 'range',
    label: 'Shadow Offset',
    min: 0,
    max: 20,
    default: 3,
    step: 1,
    unit: 'px',
  },
  {
    key: 'shadowColor',
    section: 'Effects',
    type: 'color',
    label: 'Shadow Color',
    default: '#000000',
  },
  {
    key: 'strokeWidth',
    section: 'Effects',
    type: 'range',
    label: 'Stroke Width',
    min: 0,
    max: 5,
    default: 1,
    step: 0.5,
    unit: 'px',
  },
  {
    key: 'strokeColor',
    section: 'Effects',
    type: 'color',
    label: 'Stroke Color',
    default: '#333333',
  },
  {
    key: 'glowSpread',
    section: 'Effects',
    type: 'range',
    label: 'Glow Spread',
    min: 0,
    max: 30,
    default: 6,
    unit: 'px',
  },
  {
    key: 'glowColor',
    section: 'Effects',
    type: 'color',
    label: 'Glow Color',
    default: '#bb86fc',
  },
  {
    key: 'chat-max-width',
    section: 'Effects',
    type: 'range',
    label: 'Max Width',
    min: 200,
    max: 800,
    default: 400,
    unit: 'px',
  },
  {
    key: 'chat-border-radius',
    section: 'Effects',
    type: 'range',
    label: 'Corner Radius',
    min: 0,
    max: 30,
    default: 6,
    unit: 'px',
  },

  /* ── Role Colors (username shades, matching Colour Bubble for consistency) ── */
  {
    key: 'chat-owner-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Username',
    default: '#ff8c42',
    cssVar: 'ownerUsername',
  },
  {
    key: 'chat-mod-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Mod Username',
    default: '#4296ff',
    cssVar: 'modUsername',
  },
  {
    key: 'chat-member-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Username',
    default: '#ce93d8',
    cssVar: 'memberUsername',
  },
  {
    key: 'chat-superchat-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Super Chat Username',
    default: '#ffd700',
    cssVar: 'superchatUsername',
  },
  {
    key: 'chat-membership-username',
    section: 'Role Colors',
    type: 'color',
    label: 'Membership Username',
    default: '#ffffff',
    cssVar: 'membershipUsername',
  },

  /* ── Frame ──────────────────────────────────────────────── */
  { key: 'includeFrame', section: 'Frame', type: 'toggle', label: 'Include Frame', default: false },
  {
    key: 'frameMargin',
    section: 'Frame',
    type: 'range',
    label: 'Frame Margin',
    min: 10,
    max: 100,
    default: 40,
    step: 5,
    unit: 'px',
  },
]
