import type { SettingDef } from '../types'
import { FONT_OPTIONS } from '../../utils/fonts'

export const scheme: SettingDef[] = [
  /* ── OBS ───────────────────────────────────────────────── */
  {
    key: 'chroma-key',
    section: 'OBS',
    type: 'toggle',
    label: 'Chroma Key Ready',
    default: false,
  },

  /* ── Colors ─────────────────────────────────────────────── */
  { key: 'messageBg', section: 'Colors', type: 'color', label: 'Background', default: '#1a1a2e' },
  {
    key: 'messageColor',
    section: 'Colors',
    type: 'color',
    label: 'Text Color',
    default: '#e0e0e0',
  },
  {
    key: 'usernameColor',
    section: 'Colors',
    type: 'color',
    label: 'Username Color',
    default: '#bb86fc',
  },

  /* ── Typography ─────────────────────────────────────────── */
  {
    key: 'usernameFontSize',
    section: 'Typography',
    type: 'range',
    label: 'Name Size',
    min: 10,
    max: 40,
    default: 14,
    unit: 'px',
  },
  {
    key: 'messageFontSize',
    section: 'Typography',
    type: 'range',
    label: 'Content Font Size',
    min: 10,
    max: 48,
    default: 14,
    unit: 'px',
  },
  {
    key: 'avatarSize',
    section: 'Typography',
    type: 'range',
    label: 'Avatar Size',
    min: 16,
    max: 80,
    default: 28,
    unit: 'px',
  },
  {
    key: 'chat-avatar-vertical-offset',
    section: 'Typography',
    type: 'range',
    label: 'Avatar Vertical Offset',
    min: -20,
    max: 20,
    default: 0,
    unit: 'px',
  },

  /* ── Effects ────────────────────────────────────────────── */
  {
    key: 'skewAngle',
    section: 'Effects',
    type: 'range',
    label: 'Skew Angle',
    min: -45,
    max: 45,
    default: 0,
    step: 1,
    unit: 'deg',
  },
  {
    key: 'shadowOffset',
    section: 'Effects',
    type: 'range',
    label: 'Shadow Offset',
    min: 0,
    max: 20,
    default: 3,
    step: 1,
    unit: 'px',
  },
  {
    key: 'shadowColor',
    section: 'Effects',
    type: 'color',
    label: 'Shadow Color',
    default: '#000000',
  },
  {
    key: 'strokeWidth',
    section: 'Effects',
    type: 'range',
    label: 'Stroke Width',
    min: 0,
    max: 5,
    default: 1,
    step: 0.5,
    unit: 'px',
  },
  {
    key: 'strokeColor',
    section: 'Effects',
    type: 'color',
    label: 'Stroke Color',
    default: '#333333',
  },
  {
    key: 'glowSpread',
    section: 'Effects',
    type: 'range',
    label: 'Glow Spread',
    min: 0,
    max: 30,
    default: 6,
    unit: 'px',
  },
  {
    key: 'chat-max-width',
    section: 'Effects',
    type: 'range',
    label: 'Max Width',
    min: 200,
    max: 800,
    default: 400,
    unit: 'px',
  },
  {
    key: 'chat-border-radius',
    section: 'Effects',
    type: 'range',
    label: 'Corner Radius',
    min: 0,
    max: 30,
    default: 6,
    unit: 'px',
  },

  /* ── Frame ──────────────────────────────────────────────── */
  { key: 'includeFrame', section: 'Frame', type: 'toggle', label: 'Include Frame', default: false },
  {
    key: 'frameMargin',
    section: 'Frame',
    type: 'range',
    label: 'Frame Margin',
    min: 10,
    max: 100,
    default: 40,
    step: 5,
    unit: 'px',
  },

  /* ── Common ─────────────────────────────────────────────── */
  {
    key: 'containerOpacity',
    section: 'Common',
    type: 'range',
    label: 'Container Opacity',
    min: 0,
    max: 100,
    default: 100,
    unit: '%',
  },
  {
    key: 'messageOpacity',
    section: 'Common',
    type: 'range',
    label: 'Message Opacity',
    min: 0,
    max: 100,
    default: 100,
    unit: '%',
  },
  {
    key: 'animationSpeed',
    section: 'Common',
    type: 'select',
    label: 'Animation Speed',
    default: 'normal',
    options: [
      { value: 'none', label: 'None' },
      { value: 'slow', label: 'Slow' },
      { value: 'normal', label: 'Normal' },
    ],
  },
  {
    key: 'chat-margin-left',
    section: 'Common',
    type: 'range',
    label: 'Screen Margin Left',
    min: 0,
    max: 100,
    default: 0,
    unit: 'px',
  },
  {
    key: 'chat-font-family',
    section: 'Common',
    type: 'select',
    label: 'Font Family',
    default: 'inherit',
    options: [
      { value: 'inherit', label: 'Default' },
      ...FONT_OPTIONS.map((f) => ({ value: f.value, label: f.label })),
    ],
  },

  /* ── YouTube ──────────────────────────────────────────── */
  {
    key: 'hide-youtube-generic',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Generic Messages',
    default: false,
  },
  {
    key: 'hide-youtube-header',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Chat Header',
    default: false,
  },
  {
    key: 'hide-youtube-footer',
    section: 'YouTube',
    type: 'toggle',
    label: 'Hide Chat Footer',
    default: false,
  },

  /* ── Role Colors ────────────────────────────────────────── */
  {
    key: 'ownerBg',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Background',
    default: '#3d1a00',
  },
  {
    key: 'ownerText',
    section: 'Role Colors',
    type: 'color',
    label: 'Owner Text',
    default: '#ff8c42',
  },

  {
    key: 'modBg',
    section: 'Role Colors',
    type: 'color',
    label: 'Mod Background',
    default: '#001f3d',
  },
  { key: 'modText', section: 'Role Colors', type: 'color', label: 'Mod Text', default: '#4296ff' },

  {
    key: 'memberBg',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Background',
    default: '#0d2818',
  },
  {
    key: 'memberText',
    section: 'Role Colors',
    type: 'color',
    label: 'Member Text',
    default: '#42cc8b',
  },
]
